added indices
ToBinio/matura pull request #3
Opened 2024-12-16 23:20 UTC by JonasPfeifer05

2024-12-17 05:58 UTC, oliverpk2000 reviewed
Lgtm

2024-12-17 12:50 UTC, ToBinio requested changes

2024-12-17 12:50 UTC, ToBinio commented on DBI/Speicher Und Buffer/Maintenance Effort.md
> +
could/should be expanded with some examples similar to "Zugriffszeit"

2024-12-17 12:50 UTC, ToBinio commented on DBI/Speicher Und Buffer/DBMS Architektur.md
***principle of locality***!!!

2024-12-18 09:29 UTC, oliverpk2000 commented on DBI/ISAM/Vorlage.md
? should this be here?

2024-12-18 10:00 UTC, oliverpk2000 commented on DBI/Speicher Und Buffer/DBMS Architektur.md
feels like the wrong folder for this, but we can move this later

2024-12-18 17:30 UTC, merged